# Workflow name for easy identification in the GitHub Actions UI.
name: Create Nagi Release with Velopack

# This workflow triggers on any push to the 'master' branch.
on:
  push:
    branches: [ master ]

jobs:
  build-and-release:
    runs-on: windows-latest
    
    # This strategy matrix will run the entire job 3 times, once for each platform.
    strategy:
      matrix:
        platform: [win-x64, win-x86, win-arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetches all history for all branches and tags for versioning.
          fetch-depth: 0

      - name: Get and Format Version from Project Properties
        id: get_version
        shell: bash
        run: |
          four_part_version=$(grep -oE '<AppxPackageVersion>[^<]+' Directory.Build.props | sed 's/<AppxPackageVersion>//')
          three_part_version=$(echo "$four_part_version" | sed 's/\.[0-9]\+$//')
          echo "version=$three_part_version" >> $GITHUB_OUTPUT

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install/Update vpk command-line tool
        run: dotnet tool update -g vpk --prerelease

      - name: Create appsettings.json from Secrets
        shell: pwsh
        run: |
          echo '{
            "NagiApiServer": {
              "Url": "https://nagiappapi.azure-api.net/nagi",
              "ApiKey": "${{ secrets.NAGI_API_KEY }}",
              "SubscriptionKey": "${{ secrets.NAGI_SUBSCRIPTION_KEY }}"
            }
          }' > src/Nagi.WinUI/appsettings.json # <-- CHANGE: Updated path to new project folder

      - name: Build and Package Platform
        # This step now runs once for each platform in the matrix.
        shell: pwsh
        run: |
          $p = "${{ matrix.platform }}"
          $publishDir = "./publish/$p"
          $releaseDir = "./Releases/$p"
          
          echo "Building for $p..."
          # <-- CHANGE: Updated path to the new .csproj file
          dotnet publish src/Nagi.WinUI/Nagi.WinUI.csproj -c ReleaseUnpackaged -r $p --self-contained -o $publishDir
          
          echo "Packaging for $p..."
          # NOTE: --mainExe is still Nagi.exe because of <AssemblyName> in your csproj
          vpk pack --packId Nagi --packVersion ${{ steps.get_version.outputs.version }} --mainExe Nagi.exe --packDir $publishDir -o $releaseDir --channel $p --runtime $p

      - name: Upload Build Artifact
        # This step also runs for each platform, creating a separate artifact.
        uses: actions/upload-artifact@v4
        with:
          # The artifact name is now unique for each platform.
          name: Nagi-Release-${{ steps.get_version.outputs.version }}-${{ matrix.platform }}
          # The path points to the specific release directory for that platform.
          path: ./Releases/${{ matrix.platform }}/