# Workflow name for easy identification in the GitHub Actions UI.
name: Create Nagi Release with Velopack

on:
  push:
    branches: [ master ]

jobs:
  build-and-release:
    # Run on a Windows machine, which is required for WinUI builds.
    runs-on: windows-latest
    
    # Run the job for each platform in parallel.
    strategy:
      matrix:
        platform: [win-x64, win-x86, win-arm64]

    # Grant the GITHUB_TOKEN the permissions it needs. This is essential.
    permissions:
      contents: read  # Required for actions/checkout to read the repo.
      packages: read  # Required to read from your GitHub Packages feed.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetches all history, which can be useful for versioning tools.
          fetch-depth: 0

      - name: Get and Format Version from Project Properties
        id: get_version
        shell: bash
        run: |
          four_part_version=$(grep -oE '<AppxPackageVersion>[^<]+' Directory.Build.props | sed 's/<AppxPackageVersion>//')
          three_part_version=$(echo "$four_part_version" | sed 's/\.[0-9]\+$//')
          echo "version=$three_part_version" >> $GITHUB_OUTPUT

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install/Update vpk command-line tool
        run: dotnet tool update -g vpk --prerelease

      - name: Create appsettings.json from Secrets
        shell: pwsh
        run: |
          echo '{
            "NagiApiServer": {
              "Url": "https://nagiappapi.azure-api.net/nagi",
              "ApiKey": "${{ secrets.NAGI_API_KEY }}",
              "SubscriptionKey": "${{ secrets.NAGI_SUBSCRIPTION_KEY }}"
            }
          }' > src/Nagi.WinUI/appsettings.json

      - name: Clear NuGet Caches
        run: dotnet nuget locals all --clear

      - name: Restore Dependencies
        run: dotnet restore src/Nagi.WinUI/Nagi.WinUI.csproj
        env:
          # Provide the built-in token to match the %GITHUB_TOKEN% placeholder.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Provide the actor's name to match the %GITHUB_ACTOR% placeholder.
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Build and Package Platform
        shell: pwsh
        run: |
          $p = "${{ matrix.platform }}"
          $publishDir = "./publish/$p"
          $releaseDir = "./Releases/$p"
          
          echo "Building for $p..."
          # Use --no-restore as we have a dedicated restore step.
          dotnet publish src/Nagi.WinUI/Nagi.WinUI.csproj -c ReleaseUnpackaged -r $p --self-contained -o $publishDir --no-restore
          
          echo "Packaging for $p..."
          vpk pack --packId Nagi --packVersion ${{ steps.get_version.outputs.version }} --mainExe Nagi.exe --packDir $publishDir -o $releaseDir --channel $p --runtime $p

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nagi-Release-${{ steps.get_version.outputs.version }}-${{ matrix.platform }}
          path: ./Releases/${{ matrix.platform }}/